name: matrix demo
on: workflow_dispatch
jobs:
  build:
    continue-on-error: true # to make sure all jobs are run.
    strategy:
      matrix:
        node-version: [12, 16]
        operating-system: [ubuntu-latest] # , windows-latest]
        # additional combinations, can also add new keys here.
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: dpes
        run: npm ci
      - name: build
        run: npm run build

  deploy:
    needs: build
    # can also be a path in a different repo
    uses: ./.github/workflows/reusable.yaml
    with:
      artifact-name: my-artifact
    #secret:
    #  secret-name: ${{ secrets.xyz }}