name: reusable deploy
on:
  # workflow_dispatch is manual invocation through a button.
  workflow_call:
    inputs:
      artifact-name:
        description: artifact name
        # optional
        required: false
        default: dist
        type: string # number, boolean
    outputs:
      result:
        description: result of deploy
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: echo artifact name ${{ inputs.artifact-name }}
      - name: output
        run: echo "deploying and uploading"
      - name: set result output
        io: set-result
        run: echo "::set-output name=step-result::success"
        #run: echo "step-result=success" >> $GITHUB_OUTPUT